cic:
  enabled: true
  nsPort: 443
  nsProtocol: HTTPS
  nsIP: X.X.X.X
  adcCredentialSecret: nscred
  entityPrefix: netflix
  license:
    accept: 'Yes'
  ingressClass:
    - netflix-vpx
  logLevel: INFO
  analyticsConfig:
    required: true
    timeseries:
      port: 5563
      metrics:
        enable: true
        mode: 'avro'
    distributedTracing:
      enable: true
      samplingrate: 100
    transactions:
      enable: true
      port: 5557
    endpoint:
      server: X.X.X.X
  nodeWatch: false
cpx:
  enabled: true
  cic:
    required: true
  license:
    accept: 'Yes'
  entityPrefix: cetflix
  logLevel: INFO
  ADMSettings:
    ADMIP: X.X.X.X
    loginSecret: admlogin
  analyticsConfig:
    required: true
    timeseries:
      port: 5563
      metrics:
        enable: true
        mode: 'avro'
    distributedTracing:
      enable: true
      samplingrate: 100
    endpoint:
      server: X.X.X.X
  ingressClass:
    - netflix-cpx
