apiVersion: v1
appVersion: "1.35.6"
description: A Helm chart for Citrix GSLB Controller configuring MPX/VPX.
name: citrix-gslb-controller
version: 1.35.6
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.cloud.com
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@cloud.com
- name: subashd
  email: subash.dangol@cloud.com
- name: apoorva-05
  email: apoorva.kamath@cloud.com
