#>>>adm-agent-kad-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adm-agent.fullname" . }}-kad
  labels:
    app: {{ include "adm-agent.fullname" . }}-kad
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8083
    name: kad
  selector:
    app: {{ include "adm-agent.fullname" . }}-kad
    tier: backend
#<<<adm-agent-kad-svc.yaml
---
#>>>adm-agent-redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adm-agent.fullname" . }}-redis
  labels:
    app: {{ include "adm-agent.fullname" . }}-redis
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: {{ include "adm-agent.fullname" . }}-redis
    tier: backend
#<<<adm-agent-redis-svc.yaml
---
#>>>adm-agent-core-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adm-agent.fullname" . }}
  labels:
    app: {{ include "adm-agent.fullname" . }}
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 162
    targetPort: 162
    protocol: UDP
    name: snmp
  - port: 514
    targetPort: 514
    name: syslog
    protocol: UDP
  - port: 4739
    targetPort: 4739
    name: ipfix
    protocol: UDP
  selector:
    app: {{ include "adm-agent.fullname" . }}-core
    tier: backend
#<<<adm-agent-core-svc.yaml
---
#>>>adm-agent-lic-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adm-agent.fullname" . }}-lic
  labels:
    app: {{ include "adm-agent.fullname" . }}-lic
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 27000
    targetPort: 27000
    name: licls
  - port: 7279
    targetPort: 7279
    name: licvd
  selector:
    app: {{ include "adm-agent.fullname" . }}-lic
    tier: backend
#<<<adm-agent-lic-svc.yaml
---
#>>>adm-agent-headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adm-agent.fullname" . }}-logstream
  labels:
    app: {{ include "adm-agent.fullname" . }}-logstream
    tier: backend
spec:
  clusterIP: None
  ports:
  - port: 5557
    targetPort: 5557
    name: ulfd
    protocol: TCP
  selector:
    app: {{ include "adm-agent.fullname" . }}-core
    tier: backend
#<<<adm-agent-headless-svc.yaml