{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adm-agent-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adm-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
- name: {{.}}
{{- end }}
{{- end }}
{{- end }}
---
#>>>adm-agent-clusterRoleBinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "adm-agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "adm-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: adm-agent-serviceaccount 
  namespace: {{ .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1
#<<<adm-agent-clusterRoleBinding.yaml
---
#>>>adm-agent-clusterRole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "adm-agent.fullname" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - ingresses
    - pods
    - secrets
    - nodes
    - namespaces
    - configmaps
    - clusters
    - daemonsets
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  - apiGroups:
    - ""
    resources:
    - services
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  - apiGroups:
    - ""
    resources:
    - events
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses
    - ingressclasses
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses/status
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
#<<<adm-agent-clusterRole.yaml
---
#>>>adm-agent-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: adm-agent-serviceaccount
  annotations:
    kubernetes.io/service-account.name: adm-agent-serviceaccount
type: kubernetes.io/service-account-token
#<<<adm-agent-secret.yaml