apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "cpx-license-aggregator.fullname" . }}
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
