apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cpx-license-aggregator.fullname" . }}
  labels:
    {{- include "cpx-license-aggregator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests", "certificatesigningrequests/approval"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/legacy-unknown", "kubernetes.io/kubelet-serving"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "approve"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cpx-license-aggregator.fullname" . }}
  labels:
    {{- include "cpx-license-aggregator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "cpx-license-aggregator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "cpx-license-aggregator.fullname" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpx-license-aggregator.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "cpx-license-aggregator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
- name: {{.}}
{{- end }}
{{- end }}
