apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cpx-license-aggregator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "cpx-license-aggregator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cpx-license-aggregator.labels" . | nindent 4 }}
  name: {{ include "cpx-license-aggregator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.licenseAggregator.service.type }}
  ports:
  - name: https
    port: 443
    targetPort: 443
{{- if and (eq .Values.licenseAggregator.service.type "NodePort") .Values.licenseAggregator.service.nodePort }}
    nodePort: {{ .Values.licenseAggregator.service.nodePort }}
{{- end }}
  selector:
    {{- include "cpx-license-aggregator.selectorLabels" . | nindent 4 }}
