apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: adm-disable-tls
spec:
  host: admagent.netscaler-system.svc.cluster.local   #change `netscaler-system` to namespace name where adm-agent is deployed.
  trafficPolicy:
    tls:
      mode: DISABLE


---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: coe-disable-tls
spec:
  host: coe.netscaler-system.svc.cluster.local   #change `netscaler-system` to namespace name where NetScaler Observability Exporter is deployed.
  trafficPolicy:
    tls:
      mode: DISABLE
