# YAML file for NS Logproxy service
apiVersion: v1
kind: Service
metadata:
  name: coe
  labels:
    app: coe
spec:
{{- if eq .Values.headless true }}
  clusterIP: None
{{- end}}
  ports:
    - port: 5557
      protocol: TCP
      name: lstreamd
{{- if .Values.timeseries.enabled }}
    - port: 5563
      protocol: TCP
      name: rest
{{- end}}
  selector:
      app: coe
---
{{- if eq .Values.nodePortRequired true }}
apiVersion: v1
kind: Service
metadata:
  name: coe-nodeport
  labels:
    app: coe
spec:
  type: NodePort
  ports:
    - port: 5557
      protocol: TCP
      name: lstreamd
      nodePort: {{ .Values.transaction.nodePort }}
{{- if .Values.timeseries.enabled }}
    - port: 5563
      protocol: TCP
      name: rest
      nodePort: {{ .Values.timeseries.nodePort }}
{{- end}}
  selector: 
      app: coe
---
{{- end}}
