# Default values for adm-agent-onboarding.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: quay.io/citrix/adm-agent-onboarding:1.0.0
pullPolicy: IfNotPresent
token:

admAgent:
  name: admagent
  image: quay.io/citrix/adm-agent:latest
  helperImage: quay.io/citrix/adm-agent-helper:1.0.0
  loginSecret:

adc:
  IP:
  mgmtHTTPPort: 80
  mgmtHTTPSPort: 443
  loginSecret: nslogin