apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: citrix-egressgateway-tls
spec:
  selector:
    app: citrix-egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: citrix-egressgateway-for-cnn
spec:
  host: citrix-adc-istio-egress-gateway-citrix-egress-svc.netscaler-system.svc.cluster.local #Note: Service name (Host) is dependent on the helm-chart release name. Use correct service name here.
  subsets:
  - name: cnn
