apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ns-direct-cnn-through-egress-gateway-tls
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - citrix-egressgateway-tls
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: citrix-adc-istio-egress-gateway-citrix-egress-svc.netscaler-system.svc.cluster.local #Note: Service name (Host) is dependent on the helm-chart release name. Use correct service name here.
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      - citrix-egressgateway-tls
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
