apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  redis-config: |
    appendonly yes
    maxmemory 2mb
    maxmemory-policy allkeys-lru
